### ISSUE TITLE
[FEAT] Onlook for Windows

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#143]
A downloadable Windows App for Onlook

**Comment by Shashankphatkure** [comment]
when can we expect Windows version :) eagerly waiting for it

**Comment by drfarrell** [comment]
> when can we expect Windows version :) eagerly waiting for it

Great to hear you're excited about it 😄  – while we don't have the downloadable Windows App yet, you can still use Onlook through Terminal. Follow these install instructions using your command line: 

https://github.com/onlook-dev/studio?tab=readme-ov-file#installation

If you run into issues, jump into [our Discord](https://discord.gg/z4q794aFrw) and we can help out.

**Comment by bkrmendy** [comment]
I created a PR for this https://github.com/onlook-dev/onlook/pull/199, but due to the amazing (not) devex of Github actions I couldn't test this end-to-end. The only thing I tested that the build completes successfully on `windows-latest` (workflow run on my fork here https://github.com/bkrmendy/studio/actions/runs/10512112223), but the artifacts weren't uploaded, I didn't debug why, hopefully this works as-is, will investigate further if not

**Comment by Kitenite** [comment]
Hey @bkrmendy, it only uploads the artifacts if the commit was tagged with a version (i.e. `v0.0.13`). [See this script](https://github.com/onlook-dev/onlook/blob/main/app/scripts/publish_tag.sh) `bun run publish_tag` 

It seems to build so I'll merge it in and create a release but might be good for us to upload artifacts regardless of tags.

**Comment by Kitenite** [comment]
@bkrmendy I don't have a Windows machine but how's this?
https://github.com/onlook-dev/onlook/releases/tag/untagged-2d7cd459dff34e6c5ad0

**Comment by drfarrell** [comment]
> when can we expect Windows version :) eagerly waiting for it

@Shashankphatkure you can download it at https://onlook.dev/ now 😄 

Let us know if you have any feedback!
