### ISSUE TITLE
[Bug] Scroll bar showing for mouse 

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#150]
#### Describe the bug
Scroll bar showing when mouse is connected. Nothing wrong with it just kinda ugly.
Should default to a nicer looking scrollbar or remove extra scrolls that should not be there

<img width="1728" alt="Screenshot 2024-08-13 at 3 49 27 PM" src="https://github.com/user-attachments/assets/01ed8b7a-2028-4655-ab67-7e15d5c4d425">

**Comment by yomalbalooshi** [comment]
Can i be assigned this issue?

**Comment by Kitenite** [comment]
@yomalbalooshi go for it!

**Comment by kartik-raj7** [comment]
Hey @yomalbalooshi  I was going through this issue and a found a fix 

`::webkit-scrollbar{
display:none;
}
`
You just need to add this code in the index.css file and it works perfectly let me know if you need any more help

**Comment by yomalbalooshi** [comment]
Hi @kartik-raj7 , I do agree with your fix. This will ensure that the UI remains the same whether a mouse is connected or not. I have a submitted PR #217  to reflect those changes.

**Comment by yomalbalooshi** [comment]
@Kitenite I have a suggestion to further improve the user experience with regards to the Layers panel scrolling. The current behavior when a component is selected in the canvas is that the Layers panel scrolls down to the component that is selected and highlights it. My suggestion is that instead of just scrolling vertically, the scrolling can be adjusted to move horizontally as well to the start of the component's name.

This is the current behavior. When a component is clicked, it scrolls vertically only, while horizontally it has not moved.
<img width="1440" alt="Screenshot 2024-08-25 at 11 04 25 AM" src="https://github.com/user-attachments/assets/578b7f08-657f-4fc3-9dc5-dc7c8c2750cb">

This is the suggested behavior. It scrolls both vertically and horizontally to that component.
<img width="1440" alt="Screenshot 2024-08-25 at 11 04 44 AM" src="https://github.com/user-attachments/assets/a859032d-9858-4ee6-95ed-f51d6914c79a">

This could probably be its own new issue to add. Let me know what you think!

**Comment by Kitenite** [comment]
Merged, nice work! 

I do like this idea @yomalbalooshi. Do you think there's a way for it to only scroll horizontally for the layers that are hidden to the right?
For example, If I click on "Your Orders" in the previous screenshot, we would not want to scroll to the right because it makes it covered.

**Comment by yomalbalooshi** [comment]
@Kitenite I had a quick look at the code, from what I have read online the scrollTo() method provided by react-arborist might only have support for vertical scrolling and not horizontal scrolling since it focuses on vertical trees. One way to overcome this issue could be to customize the scrolling instead of only using the scrollTo() method.

we could customize the behavior such that it only scrolls under certain conditions. One of the conditions could be to calculate how much of it is visible from the panel. If for example only 5 out of 30 letters are visible, then we would trigger the scrolling and more of the text would be visible.

Another way to customize the behavior without calculations would be to scroll horizontally every time an element is selected. However, instead of scrolling to the end of the panel, we could just scroll horizontally all the way to the icon preceding the text of the selected layer. That way if "Your Orders" was selected, it would scroll only slightly, and we would be able to see the icon+text of the layer.

**Comment by Kitenite** [comment]
@yomalbalooshi  Scrolling to the icon is very clever! I can see that working. Up to you if you'd want to give it a PR! I would try to keep the change very minimal to keep complexity low. 

Otherwise, we have a lot of higher-priority issues if you want to try another out.
