### ISSUE TITLE
[Help] After update auth is required

### ISSUE THREAD

**Issue by smndtrl** [onlook-dev/onlook#499]
Hi,
after updating Onlook suddenly displays a login screen that seems like mandatory. Did I miss a button to get around it?
Unfortunately we don't have a way to use third party oauth apps with GH or Google due to privacy and security requirements. Is there another option in case accounts are mandatory now?

**Comment by hitaspdotnet** [comment]
delete `.env` file from app's root or keep variables empty

**Comment by smndtrl** [comment]
I run the application from `/Applications/Onlook.app` and before I can do anything it asks for a sign-in. Which `.env` file is relevant for that?

**Comment by Kitenite** [comment]
Hey @smndtrl , 
You can run Onlook from source by following the instructions here:
https://github.com/onlook-dev/onlook?tab=readme-ov-file#installation

If you'd like a production-level build from that instead of running from the command line, you can run 
`npm run build` and `npm run package` in the `app` folder. Afterwhich you'll have a build you can use in `app/release`

Does that help? Happy to walk you through on a call as well :)

**Comment by Kitenite** [comment]
This is now a core functionality. Please open if this is still a blocker
