### ISSUE TITLE
[feat] Add existing functionalities to right click menu

### ISSUE THREAD

**Issue by Kitenite** [onlook-dev/onlook#524]
#### Describe the feature
Add some more of our existing functionalities to the right click
* [Insert div](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/insert/index.ts#L92) (note: for this, we'd have to choose a reasonable default size)
* [Insert text](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/insert/index.ts#L92) (note: for this, we'd have to choose a reasonable default size)
* [Copy](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/copy/index.ts#L24)
* [Duplicate](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/copy/index.ts#L98)
* [Paste](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/copy/index.ts#L53)
* [Cut](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/copy/index.ts#L93)
* [Delete](https://github.com/onlook-dev/onlook/blob/main/app/src/lib/editor/engine/element/index.ts#L146)
* [Select parent ](https://github.com/onlook-dev/onlook/blob/main/app/src/lib/editor/engine/element/index.ts#L63) (new but can be found using the selected element's parent)
* [Edit text](https://github.com/onlook-dev/onlook/blob/c396dac1ff503f1c76f72b8816ad8f572dfaa452/app/src/lib/editor/engine/text/index.ts#L13)

Coming soon:
* Wrap with div

Note: Feel free to split into multiple PRs as necessary.

<img width="205" alt="Screenshot 2024-10-14 at 11 05 38 AM" src="https://github.com/user-attachments/assets/61fc46ea-58a3-4685-816f-779856faf7f4">

**Comment by shiv-0101** [comment]
Hey Buddy🤗

Do we need to add the complete functionality or just add the above list items to the right click menu?

**Comment by Kitenite** [comment]
Hey @shiv-0101 ,
The functionalities would be great! I'll update this with some more context of where those live.

**Comment by shiv-0101** [comment]
Better now, So the functionality doesn't have to be coded from scratch, we just need to integrate it when they're clicked

**Comment by Kitenite** [comment]
@shiv-0101  Yes

**Comment by shiv-0101** [comment]
Great then, let's goo

**Comment by cleobnvntra** [comment]
Hello @Kitenite ! Im just wondering if I need to be assigned to work in this issue specifically, or can I just submit PRs of which functionalities I have implemented?

#### How it currently works
I currently have a working implementation for a few of the listed functionalities, however the way it currently works is the user has to manually click (or select) an element, so that the right click functionality knows what element is selected and to be processed.

#### In progress
I am currently figuring out a proper way to just also select the currently hovered element the moment the user presses right-click.

With that said, I was wondering if the current implementation will be acceptable for a PR? Or would it be preferred to have the functionality to select the element when right-clicking an element?

**Comment by Kitenite** [comment]
Please feel free to submit a PR @cleobnvntra. I just assigned you!
