### ISSUE TITLE
[feat] "Enter to apply" helper text and icon for Tailwind input boxes.

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#549]
"Enter to apply" text and icon that shows while the Tailwind box is focused. When the Tailwind input box is not focused, hide the helper text.
<img width="626" alt="image" src="https://github.com/user-attachments/assets/7c15d2d3-f576-4027-abeb-f137fd621ebb">

Ideally it doesn't overlap with the input text, so it may require some margin above it.

Here's the custom return icon .svg
![Return](https://github.com/user-attachments/assets/1c07a8f8-38be-45ff-9cfe-63cffa95aabc)

**Comment by cduarte3** [comment]
Hello @drfarrell , could you please assign me this issue?

**Comment by Kitenite** [comment]
Hey @cduarte3, go for it!

**Comment by cduarte3** [comment]
# Quick update

## Resizing

With the ability to resize that textArea while inputting content, there tends to be some overlap if a user makes the window shorter. This resizing ability can be kept if the "enter to apply" is placed underneath the textArea. 

**Example of placement with keeping ability to resize:**

![image](https://github.com/user-attachments/assets/3bb8cfdb-d53f-482f-b74a-bdd9fdd72d2c)


## My fix so far

So far, I have been able to implement the desired look as requested, just without that user resizing feature. I have made the textArea resize automatically so that there is always margin between the content and the "enter to apply" message.

**My changes:**

![image](https://github.com/user-attachments/assets/0c18af57-83f1-49dd-b847-6bf926f2b95e) ![image](https://github.com/user-attachments/assets/37bc303d-b562-4bea-9cce-f94192cdb2c5)


## Overall

Please let me know if my current implementation is a good idea, or if I should employ the strategy mentioned prior to this. I would think the automatic resize is better for the requested change but I am not sure if you would like to keep the user's ability to resize this textArea. Please let me know of the preference.

**Comment by Kitenite** [comment]
@cduarte3  I like the auto-resize. We can probably add a max line if it gets too long. 

I think we'd still like users to be able to resize. We can implement custom drag areas on the edge for that if the default resizer doesn't work. But I think it's worth opening a PR with what you have currently :)

**Comment by Kitenite** [comment]
Merged, nice work @cduarte3 !

**Comment by drfarrell** [comment]
Thanks for your work on this @cduarte3 it looks slick!
