### ISSUE TITLE
[feat] Improve the color styling for lightmode on the opening screen

### ISSUE THREAD

**Issue by drfarrell** [onlook-dev/onlook#579]
Make the colors more agreeable to what we have for darkmode – i.e. make custom styles that look good for this page that is shown when no projects are in Onlook.

<img width="1051" alt="image" src="https://github.com/user-attachments/assets/a156e019-281f-4b7e-b5b5-a7497fba753f">

**Comment by Kabiirk** [comment]
Hi @drfarrell !

Can you please assign this to me ?

From what I understand, I'll need to style the UI for `app/src/routes/projects/ProjectsTab/Create/ChooseMethod.tsx` to align more with what is present for the Dark Theme. Do correct me if required.

Best Regards

**Comment by Kitenite** [comment]
Hey @Kabiirk , yes precisely. There are examples of design token uses that handle both dark and light mode. Our design tokens are defined here:
https://github.com/onlook-dev/onlook/blob/827287e23c694d6b998025bfabc3ddf0ae9067a0/app/src/index.css#L5

**Comment by Kabiirk** [comment]
Thanks, I'll start working on it & share something soon.

**Comment by Kabiirk** [comment]
Hi !
Just a Sit Rep: I'm still working on this, will make a PR in some time.

**Comment by Kitenite** [comment]
Thanks for the update @Kabiirk !

**Comment by Kabiirk** [comment]
Hi guys !

Do I need to add new ` design tokens` to `index.css` ? I've only made changes to `app/.../Create/ChooseMethod.tsx` since I assume this change only affects a very specific state of the `projects` page (when there are no projects), It's going to be only once in the app.

I tried multiple color combinations & found these to be the most optimal:

#### Option 1:
Here, I stuck to your original theme, which I think looks good both in light & Dark mode. I just modified the relative color ratios (ratio between `blues` in `New Onlook project` wasn't the same as the `teals` in `Import existing project`, so I made them more 'harmonious' to each other by making the `bg-blue` a bit darker). 
1. Light
    ![image](https://github.com/user-attachments/assets/92af9b10-3bb7-4074-b304-2875728148b6)
2. Dark
    ![image](https://github.com/user-attachments/assets/d1993ad3-d554-44e6-a41e-fa431d29bc33)

-----

#### Option 2:
I thought the above changes were 'too few' for the PR, so I imposter-syndrom-ed myself & made a different color scheme 🙃 
Since Gray usually denotes `secondary` buttons/text etc, I used them as the same, & retained blue as the 'primary' color (primay colors in `index.css` tokens are white, secondary & tertiary are too close to each other, so I did not use those).
1. Light
    ![image](https://github.com/user-attachments/assets/607000a9-10cc-442c-8296-b7b44362b32a)

2. Dark
    ![image](https://github.com/user-attachments/assets/9a1f40f3-1ede-4380-8da8-978b20039639)



Let me know which you think is better & I'll proceed with the PR.

**Comment by Kitenite** [comment]
@drfarrell , please give your input. If possible, recommend if we have an existing token. Otherwise I think it makes sense to add once if we need to.

**Comment by drfarrell** [comment]
@Kabiirk the colors should be more of a "light-mode" inversion of the dark mode colors. So if the spectrum of colors is 50-950 with

**50 100 200 300 400 500 600 700 800 900 950**

Then you can probably get pretty close by just flipping the spectrum the other way around for light mode.

**950 900 800 700 600 500 400 300 200 100 50**

So if something is dark:teal-800 in dark mode, you can assign in teal-200 to get light mode. 

This isn't perfect, but will get you closer to what the colors should look like in light mode. Try making these cards feel "light" by first inverting the number for that class in light mode, and then choosing adjacent numbers until it "feels" lighter, because the current configuration is too dark against the white background.

![image](https://github.com/user-attachments/assets/7c1b632d-8bcf-4e95-86ba-8a9b440e8940)

**Comment by Kabiirk** [comment]
Hi @drfarrell ,

Thanks for the pointers ! I followed the "inversion" approach (with modifications) for a better colors in Light & dark mode. 

# Option 1
![Option 1](https://github.com/user-attachments/assets/553aee9b-fdc8-4042-87aa-9f70bbda44de)

# Option 2
![Option 2](https://github.com/user-attachments/assets/0d81e719-4393-4738-93e4-c3d359e68f68)

Let me know which one you like, & I'll make the PR.

**Comment by drfarrell** [comment]
@Kabiirk option 2 looks much better yes. Can you plz make the PR? I can review it
