### ISSUE TITLE
Made changes regarding Div but the editor is stuck on "writing code"

### ISSUE THREAD

**Issue by LucasThin** [onlook-dev/onlook#793]
#### Describe the bug
<img width="1075" alt="Screenshot 2024-11-17 at 3 54 52 PM" src="https://github.com/user-attachments/assets/38ec087a-639c-418c-ac7c-4a39354c2a49">
Added Div / group the card-header content.
Then added a new div.
Changed the card-header to be flex direction ->.
It just says writing code on the top. no code was changed on the backend. 
Only editing text had changes applied.  Tried twice with nothing.

**Comment by Kitenite** [comment]
@LucasThin , thanks for reporting. What happens if you hit the refresh button on the top bar? Seems like the UI might've gotten out of sync with the code. Something I'm actively working on fixing rn.

<img width="404" alt="Screenshot 2024-11-17 at 9 38 09 PM" src="https://github.com/user-attachments/assets/e101827d-1174-4439-9653-edb7b0eeab78">

**Comment by Kitenite** [comment]
@LucasThin this is now fixed :)
