### ISSUE TITLE
[bug] "Onlook Not Enabled for the Project" Persisting & Play Button Not Working

### ISSUE THREAD

**Issue by TroyRobinson** [onlook-dev/onlook#838]
#### Describe the bug
Forward: Thank you for your ongoing work on Onlook. I am a fan of your vision (in the spirit of a practical Utopia.app or @HadronApp). And I would love to work for your company one day when you blow up. (I'm a UX/UI designer/front-end-developer for enterprise dashboards and enjoy prototyping new UI design tools in my spare time)

The Bug --> Even though I set up the project with Onlook and I again used the terminal in the project folder to set up onlook via "npx onlook setup", I still kept getting the error  "Onlook Not Enabled for the Project" and it wouldn't play. I fully closed out the app and reopened it and yet the same bug persisted. I reset my computer (Mac Mini M4) and the project then started working again. 

Now the error shows up when the project is opened although goes away after I click play and the app boots up.

Another related bug, during the time when I couldn't press play, I would click on the Onlook logo to go back to all my projects and nothing would happen.

Thanks again for your help!
- Troy

**Comment by Kitenite** [comment]
Thanks for the report and the kind words, @TroyRobinson ! 

> Even though I set up the project with Onlook and I again used the terminal in the project folder to set up onlook via "npx onlook setup"

The `npx onlook setup` script will no longer be necessary as of the latest updates. There will no longer be a setup step. Onlook will just work for each React project once the play button is hit  :) 

However, you will have to run the project in the Onlook play button instead of from your terminal which is why the onlook not enabled warning was on. Sorry if this change wasn't communicated well. I'll be sure to update the instructions from the warning. 

Are you still having any issues even from the play button?

**Comment by Kitenite** [comment]
Updated documentation and add better state handling for when onlook is running vs not. Thanks for the issue @TroyRobinson 
https://github.com/onlook-dev/onlook/pull/843

**Comment by TroyRobinson** [comment]
Hi Kitenite, thank you for your attention and for the update. To answer your question, the issues remained even when pressing the play button. Nothing would happen when play was pressed. Even resetting the program and pressing play didn't resolve. Only resetting the computer did the trick, and the play button started working again. I hope that makes sense.

**Comment by Kitenite** [comment]
@TroyRobinson , this is identified to be a dangling process by us not handling exit modes correctly. This should be fixed now but please let me know if it persists. Thanks :)
